apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tfserving-pvc
spec:
  # volumeName: tfserving-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage}}