apiVersion: v1
kind: Secret
metadata:
  name: tfserving-credentials
data:
  AWS_ACCESS_KEY_ID: {{ .Values.tfservingCredentials.AWS_ACCESS_KEY_ID  | b64enc}}
  AWS_SECRET_ACCESS_KEY: {{ .Values.tfservingCredentials.AWS_SECRET_ACCESS_KEY  | b64enc}}