apiVersion: v1
kind: Secret
metadata:
  name: datasetsharing-credentials
data:
  POSTGRES_HOST: {{ .Values.datasetsharingCredentials.POSTGRES_HOST  | b64enc}}
  POSTGRES_PORT: {{ .Values.datasetsharingCredentials.POSTGRES_PORT  | b64enc}}
  POSTGRES_USER: {{ .Values.datasetsharingCredentials.POSTGRES_USER  | b64enc}}
  POSTGRES_PASSWORD: {{ .Values.datasetsharingCredentials.POSTGRES_PASSWORD  | b64enc}}
  POSTGRES_DBNAME: {{ .Values.datasetsharingCredentials.POSTGRES_DBNAME  | b64enc}}
  MINIO_URL: {{ .Values.datasetsharingCredentials.MINIO_URL  | b64enc}}
  MINIO_PORT: {{ .Values.datasetsharingCredentials.MINIO_PORT  | b64enc}}
  MINIO_USER: {{ .Values.datasetsharingCredentials.MINIO_USER  | b64enc}}
  MINIO_PASSWORD: {{ .Values.datasetsharingCredentials.MINIO_PASSWORD  | b64enc}}
  MINIO_BUCKET: {{ .Values.datasetsharingCredentials.MINIO_BUCKET  | b64enc}}