{{- if .Values.datasetsharingIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-datasetsharing
  labels:
    app: ingress-datasetsharing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/datasetsharing)$ $1/ permanent;
      sub_filter 'href="/' 'href="/datasetsharing/';
      sub_filter 'src="/' 'src="/datasetsharing/';
      sub_filter '/openapi.json' '/datasetsharing/openapi.json';
      sub_filter_once off;
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /datasetsharing(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: datasetsharing-service
                port: 
                  number: 8080
{{- end }}