apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
data:
  POSTGRES_USER: {{ .Values.postgresCredentials.POSTGRES_USER  | b64enc}}
  POSTGRES_PASSWORD: {{ .Values.postgresCredentials.POSTGRES_PASSWORD | b64enc}}
