{{- if .Values.grpcApi2Ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grpc-api2-ingress-torchserver
  labels:
    app: grpc-api2-ingress-torchserver
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /grpcapi2(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: torchserve-service-grpc-api-2
                port: 
                  number: 7071
{{- end }}