apiVersion: v1
kind: Service
metadata:
  name: torchserve-service-grpc-api-2
  labels:
    app: torchserve-service-grpc-api-2
  {{- if .Values.grpcApi2Service.annotations }}
  annotations: {{- toYaml .Values.grpcApi2Service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.grpcApi2Service.type }}
  {{- if and (eq .Values.grpcApi2Service.type "ClusterIP") .Values.grpcApi2Service.clusterIP }}
  clusterIP: {{ .Values.grpcApi2Service.clusterIP }}
  {{- end }}
  ports:
    - name: torchserve-grpc-api-2
      port: 7071
      protocol: TCP
      {{- if (and (eq .Values.grpcApi2Service.type "NodePort") ( .Values.grpcApi2Service.nodePort)) }}
      nodePort: {{ .Values.grpcApi2Service.nodePort }}
      {{- else }}
      targetPort: 7071
      {{- end }}
  selector:
    app: torchserve