{{- if .Values.restInferenceIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-inference-ingress-torchserver
  labels:
    app: rest-inference-ingress-torchserver
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /restinference(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: torchserve-service-rest-inference
                port: 
                  number: 8080
{{- end }}