apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
data:
  MINIO_ROOT_USER: {{ .Values.minioCredentials.MINIO_ROOT_USER  | b64enc}}
  MINIO_ROOT_PASSWORD: {{ .Values.minioCredentials.MINIO_ROOT_PASSWORD  | b64enc}}