apiVersion: v1
kind: Secret
metadata:
  name: timescale-credentials
data:
  POSTGRES_USER: {{ .Values.timescaleCredentials.POSTGRES_USER  | b64enc}}
  POSTGRES_PASSWORD: {{ .Values.timescaleCredentials.POSTGRES_PASSWORD | b64enc}}
