apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
data:
  PGADMIN_EMAIL: {{ .Values.pgadminCredentials.PGADMIN_EMAIL  | b64enc}}
  PGADMIN_PASSWORD: {{ .Values.pgadminCredentials.PGADMIN_PASSWORD | b64enc}}