apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin-service
  {{- if .Values.consoleService.annotations }}
  annotations: {{- toYaml .Values.consoleService.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.consoleService.type }}
  {{- if and (eq .Values.consoleService.type "ClusterIP") .Values.consoleService.clusterIP }}
  clusterIP: {{ .Values.consoleService.clusterIP }}
  {{- end }}
  ports:
    - name: pgadmin-console
      port: 80
      protocol: TCP
      {{- if (and (eq .Values.consoleService.type "NodePort") ( .Values.consoleService.nodePort)) }}
      nodePort: {{ .Values.consoleService.nodePort }}
      {{- else }}
      targetPort: 80
      {{- end }}
  selector:
    app: pgadmin-ui-service