
replicaCount: 1

imageCredentials:
  enabled: false
  registry: xxxx
  username: xxxx
  password: xxxx
  email: xxxx

image:
  repository: datasetsharing-api
  tag: 1.0.0

datasetsharingCredentials:
  POSTGRES_HOST: timescale-service.default.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_USER: xxxx
  POSTGRES_PASSWORD: xxxx
  POSTGRES_DBNAME: datasetsharing
  MINIO_URL: minio-service-api.default.svc.cluster.local
  MINIO_PORT: "9000"
  MINIO_USER: xxxx
  MINIO_PASSWORD: xxxx
  MINIO_BUCKET: datasetsharing-registry


datasetsharingService:
  type: ClusterIP
  clusterIP: ~
  nodePort: 30080
  loadBalancerIP: ~
  annotations: {}


datasetsharingIngress:
  enabled: true


