FROM python:3.10-slim

WORKDIR /app
USER root

COPY . .
RUN pip install -r requirements.txt && chmod +x /app/entrypoint_modelsharing_api.sh

ENV PYTHONPATH="/app"

ENTRYPOINT [ "/app/entrypoint_modelsharing_api.sh"]

EXPOSE 8080