openapi: 3.0.3
info:
  title: Machine Learning Model Sharing - OpenAPI 3.0
  description: |-
    Machine Learning Model Sharing OpenAPI definition
  termsOfService: http://swagger.io/terms/
  contact:
    email: imasd@optaresolutions.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://mlops.sustainability.hexaxii.org/api/v1
tags:
  - name: model
    description: ML Model API
  - name: health
    description: Health check API
paths:
  /health:
    get:
      tags:
        - health
      summary: Test service Health
      description: Service Health Check
      operationId: getHealth
  /api/v1/model:
    post:
      tags:
        - model
      summary: addModel
      description: Add a new model with metainfo
      operationId: postModel
      security:
        - model_auth:
            - write:model
            - read:model
  /api/v1/model/{modelId}/parameters:
    post:
      tags:
        - model
      summary: addModelParameters
      description: Add model parameters
      operationId: postModelParameters
      security:
        - model_auth:
          - write:model
          - read:model
    put:
      tags:
        - model
      summary: updateModelParameters
      description: Update model parameters
      operationId: putModelParameters
      security:
        - model_auth:
          - write:model
          - read:model
  /api/v1/model/{modelId}/characteristics:
    post:
      tags:
        - model
      summary: addModelCharacteristics
      description: Add model metainfo
      operationId: postModelCharacteristics
      security:
        - model_auth:
          - write:model
          - read:model
    put:
      tags:
        - model
      summary: updateModelCharacteristics
      description: Update model metainfo
      operationId: putModelCharacteristics
      security:
        - model_auth:
          - write:model
          - read:model
  /api/v1/model/{modelId}:
    get:
      tags:
        - model
      summary: getModelByIdAndVersion
      description: Service to get a model by model Id and version (default value 'latest')
      operationId: getModel
      security:
        - model_auth:
            - read:model
    delete:
        tags:
          - model
        summary: deleteModelByIdAndVersion
        description: Service to delete a model and metainfo by model Id
        operationId: deleteModel
        security:
        - model_auth:
            - write:model
            - read:model
    patch:
        tags:
          - model
        summary: patchModelMetaInfo
        description: Service to update model information by model Id
        operationId: patchModel
        security:
        - model_auth:
            - write:model
            - read:model
    put:
        tags:
          - model
        summary: updateModel
        description: Service to get a model by model Id
        operationId: updateModel
        security:
        - model_auth:
            - write:model
            - read:model
  /api/v1/model/{modelId}/data:
    get:
      tags:
        - model
      summary: getModelInfo
      description: Service to get a model by model Id
      operationId: getModelInfo
      security:
        - model_auth:
            - read:model
  /api/v1/model/catalog:
    get:
      tags:
        - model
      summary: getModelCatalogByFilters
      description: Service to get a model by model Id
      operationId: getModelCatalog
      security:
        - model_auth:
            - read:model
components:
  securitySchemes:
    model_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://mlops.sustainability.hexaxii.org/api/v1
          scopes:
            write:model: add and update models and info
            read:model: get model anf models info
    api_key:
      type: apiKey
      name: api_key
      in: header