{{- if .Values.modelsharingIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-modelsharing
  labels:
    app: ingress-modelsharing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/modelsharing)$ $1/ permanent;
      sub_filter 'href="/' 'href="/modelsharing/';
      sub_filter 'src="/' 'src="/modelsharing/';
      sub_filter '/openapi.json' '/modelsharing/openapi.json';
      sub_filter_once off;
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /modelsharing(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: modelsharing-service
                port: 
                  number: 8080
{{- end }}